### ISSUE TITLE
topics are imported in reverse-order

### ISSUE THREAD

**Issue by indirectlylit** [ralphiee22/ka-sushi-chef#1]
Originally reported here: https://github.com/learningequality/kolibri/issues/621

Khan Academy: 

![image](https://cloud.githubusercontent.com/assets/2367265/20845835/bd4e4326-b87b-11e6-8210-f0e9f35fb010.png)

vs Kolibri: 

![image](https://cloud.githubusercontent.com/assets/2367265/20845841/c768ea0a-b87b-11e6-99b4-288a051d427e.png)

**Comment by ralphiee22** [comment]
This is actually addressed here https://github.com/ralphiee22/ka-sushi-chef/blob/master/ka_sushi_chef.py#L32.
That channel was made before I added in this change.
But I still wanted to look into to it so I don't have that to do that manual reverse, so I will leave this open.

**Comment by indirectlylit** [comment]
that work-around seems fine, if this is just a general inconsistency between orders in our two systems. Is there potentially a different underlying problem?

**Comment by ralphiee22** [comment]
There is no underlying problem. I will add a comment specifying that the reversal is needed based on structure of data.
